{% set name = "cmplxfoil" %}
{% set version = "2.1.1" %}

package:
  name: cmplxfoil
  version: {{ version }}

source:
  url: https://github.com/mdolab/{{ name|upper }}/archive/v{{ version }}.tar.gz
  sha256: 7015a98c5afb72cdcf8c935fdf9a19e5fbba2ca7646d2dedb00682349c539943
  patches:
    - FC-config-linux.patch
    - f2py-no-fcompiler.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
    - meson  # [py>=312]
    - numpy  # [py>=312]
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mdolab-baseclasses

test:
  imports:
    - cmplxfoil

about:
  home: https://github.com/mdolab/CMPLXFOIL/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: CMPLXFOIL is a version of Mark Drela's XFOIL code with the GUI features removed.
  description: |
    CMPLXFOIL is a version of Mark Drela's XFOIL code with the GUI features removed. 
    Gradient computation is implemented with the complex-step method.
  doc_url: https://mdolab-cmplxfoil.readthedocs-hosted.com/
  dev_url: https://github.com/mdolab/CMPLXFOIL/

extra:
  recipe-maintainers:
    - eytanadler
    - A-CGray
    - bernardopacini
    - whophil
